name: Bug Report
description: A clear and concise description of what the bug is.
labels: Bug

body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: A clear and concise description of the problem
      validations:
          required: true
    - type: textarea
      id: possible-solution
      attributes:
          label: Possible Solution
          description: |
            Optional: only if you have suggestions on a fix/reason for the bug
    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: "Optional: any other context about the problem: log messages, screenshots, etc."
